#############################################################################
# Copyright (c) 2019 Cisco and/or its affiliates.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##############################################################################

FROM openjdk:8-jdk

MAINTAINER Angelo Mantellini <manangel@cisco.com>

ENV VERBOSE=1

ENV ANDROID_COMPILE_SDK="27"        \
    ANDROID_BUILD_TOOLS="28.0.3"    \
    ANDROID_SDK_TOOLS_REV="4333796" \
    ANDROID_CMAKE_REV="3.6.4111459" \
    ANDROID_CMAKE_REV_3_10="3.10.2.4988404"

ENV ANDROID_HOME=/opt/android-sdk-linux
ENV PATH ${PATH}:${ANDROID_HOME}/platform-tools/:${ANDROID_NDK_HOME}:${ANDROID_HOME}/ndk-bundle:${ANDROID_HOME}/tools/bin/

RUN apt-get update && \
    apt-get install -y file make && \
    rm -rf /var/lib/apt/lists/*

RUN uname -a

RUN apt-get update
RUN apt-get install -y \
	libdbus-1-3 \
    libgl1-mesa-glx \
	libglib2.0-0 \
	&& apt-get clean

#RUN mkdir -p /tmp/qt-installer \
#	cd /tmp/qt-installer \
#	&& wget -v https://raw.githubusercontent.com/homdx/qtci/master/bin/extract-qt-installer --directory-prefix=/tmp/qt-installer/ \
#	&& wget -v https://raw.githubusercontent.com/homdx/qtci/master/recipes/install-qt --directory-prefix=/tmp/qt-installer/ \
#	&& export PATH=$PATH:/tmp/qt-installer/ \
#	&& chmod u+rx /tmp/qt-installer/extract-qt-installer \
#	&& chmod u+rx /tmp/qt-installer/install-qt \
#	&& bash /tmp/qt-installer/install-qt $QT_VERSION \
#	&& rm -rf /tmp/qt-installer

ENV QT_HOME=/opt/Qt
ENV QT_VERSION=5.13.1
RUN git clone https://github.com/benlau/qtci.git

ENV PATH PATH=$PATH:$PWD/qtci/bin:$PWD/qtci/recipes
ENV QT_CI_PACKAGES=qt.qt5.5131.android_arm64_v8a,qt.qt5.5131.qtcharts.android_arm64_v8a,qt.qt5.5131.qtcharts
RUN cd /opt && install-qt 5.13.1 && rm *.run

RUN    mkdir -p ${ANDROID_HOME} \
    && wget --quiet --output-document=${ANDROID_HOME}/android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_TOOLS_REV}.zip \
    && unzip -qq ${ANDROID_HOME}/android-sdk.zip -d ${ANDROID_HOME} \
    && rm ${ANDROID_HOME}/android-sdk.zip \
    && mkdir -p $HOME/.android \
    && echo 'count=0' > $HOME/.android/repositories.cfg

RUN    yes | sdkmanager --licenses > /dev/null \ 
    && yes | sdkmanager --update \
    && yes | sdkmanager 'tools' \
    && yes | sdkmanager 'platform-tools' \
    && yes | sdkmanager 'build-tools;'$ANDROID_BUILD_TOOLS \
    && yes | sdkmanager 'platforms;android-'$ANDROID_COMPILE_SDK \
    && yes | sdkmanager 'platforms;android-28' \
    && yes | sdkmanager 'extras;android;m2repository' \
    && yes | sdkmanager 'extras;google;google_play_services' \
    && yes | sdkmanager 'extras;google;m2repository' 

RUN    yes | sdkmanager 'cmake;'$ANDROID_CMAKE_REV \
    && yes | sdkmanager --channel=3 --channel=1 'cmake;'$ANDROID_CMAKE_REV_3_10 \
    && yes | sdkmanager 'ndk-bundle'

ENV ANDROID_NDK_HOME=/opt/android-sdk-linux/ndk-bundle/
