name: Publish Docker Android Build with hICN stack
on:
  schedule:
    - cron:  '0 1 * * *'
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: icn-team/android-build/hicn:latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.pkg.github.com
        dockerfile: Dockerfile_hicn
        buildargs: DOCKER_IMAGE=docker.pkg.github.com/icn-team/android-build/dep
