name: Docker Android Build with android APKs
on:
  schedule:
    - cron:  '0 0 1 */6 *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: icn-team/android-build/hapk:latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.pkg.github.com
        dockerfile: Dockerfile_hapk
        buildargs: DOCKER_IMAGE=docker.pkg.github.com/icn-team/android-build/hicn